[package]
name = "o3k-api"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
axum.workspace = true
o3k-identity = { path = "../o3k-identity" }
o3k-image = { path = "../o3k-image" }
o3k-network = { path = "../o3k-network" }
serde.workspace = true
uuid.workspace = true

[dev-dependencies]
http.workspace = true
o3k-identity = { path = "../o3k-identity" }
serde_json.workspace = true
tokio.workspace = true
tower.workspace = true
