[package]
name = "o3k-compute"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
o3k-provider = { path = "../o3k-provider" }
o3k-reconciler = { path = "../o3k-reconciler" }
o3k-store = { path = "../o3k-store" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
