#!/bin/sh
set -eu

if [ "${1:-}" = "--test" ]; then
    exit 0
fi

for arg in "$@"; do
    case "$arg" in
        --pid-file=*) echo "$$" > "${arg#--pid-file=}" ;;
    esac
done

trap 'exit 0' TERM INT
while :; do
    sleep 1
done
