#!/usr/bin/env bash
# upgrade-process.sh — process-level test for the real `o3k` binary's
# upgrade/rollback state machine (issue #626, docs/plan/o3k-upgrade.md §13.2).
#
# Deterministic, rootless, and offline: everything the upgrade engine could
# touch is a private mktemp sandbox driven through the engine's sandbox
# overrides (O3K_UPGRADE_PREFIX / _BIN_DIR / _CONFIG_DIR / _DATA_DIR /
# _STATE_FILE / _BACKUP_DIR / _DOWNLOAD_DIR), PATH shims for systemctl /
# virsh / ip / df / ps / curl, loopback health shims on the standard
# 127.0.0.1:18080 (control) and 127.0.0.1:9100 (compute) ports, and a local
# python3 release endpoint serving fixture tarballs generated by a small
# deterministic builder. No root is required; the script SKIPs with an
# explicit message when a prerequisite is missing (mirroring
# tests/doctor-process.sh and tests/installer-negative.sh).
#
# Engine-interface contract (kept in sync with the Rust implementation;
# see docs/plan/o3k-upgrade.md):
#   - release resolution/download goes through the PATH `curl` shim, which
#     rewrites github.com/api.github.com URLs onto the local fixture endpoint
#     (the same SystemExec seam the doctor uses). If the engine later adopts
#     an internal HTTP client for downloads, it must honor an equivalent
#     override so this test stays offline.
#   - the concurrent-invocation lock is `<state-file>.lock` (O_EXCL with
#     dead-pid reclaim — the engine's unsafe-free equivalent of the plan §2
#     flock; the test pre-creates it with a live pid).
#   - `upgrade --check` is read-only; `--yes` keeps mutation cases
#     noninteractive; `--json` emits the plan §1 document
#     (source_version, target_version, phase, backup_id, status,
#     rollback_performed, doctor_status).
#   - COMMITTED clears the in-progress state file and records the backup in
#     <backup-dir>/backup-chain.json (plan §2).
#
# Every case asserts three things: the exit code, the state file
# phase/status (absent counts as a pinned assertion where the plan clears
# it), and that no foreign fixture file was modified (byte-level snapshot of
# binaries, manifests, config, and database).
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/o3k-upgrade-process.XXXXXX")"
chmod 0755 "$WORK_DIR" # unprivileged engine runs must be able to traverse it
OUT_DIR="$WORK_DIR/outputs"
mkdir -p "$OUT_DIR"
SERVER_PIDS=()
PASS=0
FAIL=0
SKIP=0

cleanup() {
  local pid
  for pid in "${SERVER_PIDS[@]}"; do kill "$pid" 2>/dev/null || true; done
  if [[ "${O3K_UPGRADE_TEST_KEEP:-0}" != 1 ]]; then
    rm -rf -- "$WORK_DIR"
  else
    printf 'kept work dir: %s\n' "$WORK_DIR" >&2
  fi
}
trap cleanup EXIT

record_pass() { PASS=$((PASS + 1)); printf 'ok   %s\n' "$1"; }
record_fail() { FAIL=$((FAIL + 1)); printf 'FAIL %s\n' "$1"; }
record_skip() { SKIP=$((SKIP + 1)); printf 'skip %s\n' "$1"; }

for tool in python3 tar sha256sum mktemp grep sed strings sort; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    record_skip "upgrade-process tests need $tool"
    printf 'upgrade process tests: %d passed, %d failed, %d skipped\n' "$PASS" "$FAIL" "$SKIP"
    exit 0
  fi
done

free_port() {
  python3 -c 'import socket; s = socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()'
}

# ------------------------------------------------------------------ shims ----

SHIM_BIN="$WORK_DIR/shim-bin"
mkdir -p "$SHIM_BIN"

# systemctl: stateful fake recording every stop/start in a per-case log and
# tracking active units in a per-case state dir. Both units start ACTIVE for
# a healthy sandbox; stop/start flip them.
cat >"$SHIM_BIN/systemctl" <<'EOF'
#!/usr/bin/env bash
# TEST FIXTURE — stateful fake systemctl; never touches the real host.
log() { printf '%s\n' "$*" >>"${O3K_TEST_SYSTEMCTL_LOG:?}"; }
case "$*" in
  *is-active*o3kd.service*)
    if [ -f "${O3K_TEST_SYSTEMCTL_STATE:?}/o3kd.active" ]; then printf 'active\n'; exit 0; else exit 3; fi ;;
  *is-active*o3k-compute.service*)
    if [ -f "${O3K_TEST_SYSTEMCTL_STATE:?}/compute.active" ]; then printf 'active\n'; exit 0; else exit 3; fi ;;
  *stop*o3k-compute.service*) log "$*"; rm -f "${O3K_TEST_SYSTEMCTL_STATE:?}/compute.active"; exit 0 ;;
  *stop*o3kd.service*) log "$*"; rm -f "${O3K_TEST_SYSTEMCTL_STATE:?}/o3kd.active"; exit 0 ;;
  *start*o3kd.service*) log "$*"; touch "${O3K_TEST_SYSTEMCTL_STATE:?}/o3kd.active"; exit 0 ;;
  *start*o3k-compute.service*) log "$*"; touch "${O3K_TEST_SYSTEMCTL_STATE:?}/compute.active"; exit 0 ;;
  *) log "$*"; exit 0 ;;
esac
EOF

# virsh: a reachable qemu:///system URI with an empty domain list — the
# healthy sandbox has no compute instances, so domains are consistent.
cat >"$SHIM_BIN/virsh" <<'EOF'
#!/usr/bin/env bash
# TEST FIXTURE — reachable libvirt with no domains.
case "$*" in
  *uri*) printf 'qemu:///system\n' ;;
  *list*) printf '\n' ;;
esac
exit 0
EOF

# ip: a stable link list containing the owned bridge o3k-br0 and no stale
# O3K TAPs.
cat >"$SHIM_BIN/ip" <<'EOF'
#!/usr/bin/env bash
# TEST FIXTURE — stable minimal link listing.
printf '1: lo: <LOOPBACK,UP,LOWER_UP>\n'
printf '2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP>\n'
printf '3: o3k-br0: <BROADCAST,MULTICAST,UP,LOWER_UP>\n'
exit 0
EOF

# df: plenty of space by default; O3K_TEST_DF_MODE=tiny simulates the
# insufficient-disk preflight case.
cat >"$SHIM_BIN/df" <<'EOF'
#!/usr/bin/env bash
# TEST FIXTURE — controlled free-space report.
if [ "${O3K_TEST_DF_MODE:-plenty}" = tiny ]; then
  printf 'Filesystem 1024-blocks Used Available Capacity Mounted on\n/dev/test 1000000 999990 10 100%% /\n'
else
  printf 'Filesystem 1024-blocks Used Available Capacity Mounted on\n/dev/test 100000000 1000000 90000000 2%% /\n'
fi
exit 0
EOF

# ps: forwards to the real ps (/proc reads stay real; the sandbox has no
# dnsmasq pidfiles, so the dhcp check stays NOT_APPLICABLE).
cat >"$SHIM_BIN/ps" <<'EOF'
#!/usr/bin/env bash
exec /bin/ps "$@"
EOF

# curl: rewrites GitHub release/API URLs onto the local fixture endpoint and
# delegates everything else (including the rewritten URL) to the real curl.
cat >"$SHIM_BIN/curl" <<'EOF'
#!/usr/bin/env bash
# TEST FIXTURE — URL rewriting proxy around the real curl. The fixture
# endpoint is served by the test's own python3 http.server; no external
# network is ever contacted by a successful rewrite.
url=""
rewritten=""
for arg in "$@"; do
  case "$arg" in
    http://*|https://*) url="$arg" ;;
  esac
done
if [ -n "$url" ]; then
  case "$url" in
    https://api.github.com/repos/kubedoio/o3k-rust/*)
      rewritten="${O3K_TEST_ENDPOINT:?}/api/${url#https://api.github.com/repos/kubedoio/o3k-rust/}" ;;
    https://github.com/kubedoio/o3k-rust/releases/download/*)
      rewritten="${O3K_TEST_ENDPOINT:?}/releases/${url#https://github.com/kubedoio/o3k-rust/releases/download/}" ;;
    https://github.com/kubedoio/o3k-rust/releases/*)
      rewritten="${O3K_TEST_ENDPOINT:?}/releases/${url#https://github.com/kubedoio/o3k-rust/releases/}" ;;
    *) rewritten="$url" ;;
  esac
fi
out=()
for arg in "$@"; do
  if [ -n "$rewritten" ] && [ "$arg" = "$url" ]; then out+=("$rewritten"); else out+=("$arg"); fi
done
exec /usr/bin/curl "${out[@]}"
EOF

# o3k: only used when the engine shells out to `o3k doctor` instead of
# running the checks in-process; answers with a canned healthy/unhealthy
# document driven by O3K_TEST_DOCTOR_SHIM_MODE.
cat >"$SHIM_BIN/o3k" <<'EOF'
#!/usr/bin/env bash
# TEST FIXTURE — subprocess doctor stub.
case "$*" in
  *doctor*)
    printf '%s\n' "$*" >>"${O3K_TEST_SYSTEMCTL_LOG:?}"
    if [ "${O3K_TEST_DOCTOR_SHIM_MODE:-healthy}" = unhealthy ]; then
      printf '{"version":"1","overall_status":"unhealthy","checks":[{"id":"control.healthz","status":"FAIL"}]}\n'
      exit 1
    fi
    printf '{"version":"1","overall_status":"healthy","checks":[]}\n'
    exit 0
    ;;
  *) exit 2 ;;
esac
EOF

chmod 0755 "$SHIM_BIN/systemctl" "$SHIM_BIN/virsh" "$SHIM_BIN/ip" \
  "$SHIM_BIN/df" "$SHIM_BIN/ps" "$SHIM_BIN/curl" "$SHIM_BIN/o3k"

# ----------------------------------------------------- release fixtures ------

INSTALLED_VERSION="0.2.0-alpha.2"
TARGET_VERSION="0.3.0-alpha.1"
FENCED_VERSION="0.4.0-alpha.1"
DOWNGRADE_TARGET="0.2.0-alpha.1"
SCHEMA_VERSION="17"

# build_release_tarball VERSION SCHEMA MIN_VERSION OUT — builds a
# deterministic release bundle tarball (manifest.json + SHA256SUMS + the
# three binaries + packaging/get-o3k.sh as the published installer wrapper
# + packaging/install.sh as the state installer) whose SHA256SUMS covers
# exactly the regular files, with installer_sha256 naming
# packaging/get-o3k.sh (mirroring make-release.sh's export).
build_release_tarball() {
  python3 - "$1" "$2" "$3" "$4" <<'PY'
import hashlib
import io
import json
import pathlib
import sys
import tarfile

version, schema, min_version, out = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
root = pathlib.Path(f"o3k-{version}")
bundle = {}
for name in ("o3kd", "o3k", "o3k-compute"):
    bundle[f"bin/{name}"] = f"fixture release binary {name} {version}\n".encode()
bundle["packaging/get-o3k.sh"] = (
    "#!/usr/bin/env bash\n"
    "# TEST FIXTURE — the published one-line installer wrapper.\n"
    "printf 'wrapper %s\\n' \"$*\" >>\"${O3K_TEST_SCRIPT_LOG:?}\"\n"
    "exit 0\n"
).encode()
bundle["packaging/install.sh"] = (
    "#!/usr/bin/env bash\n"
    "# TEST FIXTURE — the state installer; records its invocation.\n"
    "printf 'install %s\\n' \"$*\" >>\"${O3K_TEST_SCRIPT_LOG:?}\"\n"
    "exit 0\n"
).encode()
installer_sha = hashlib.sha256(bundle["packaging/get-o3k.sh"]).hexdigest()
manifest = {
    "version": version,
    "profile": "libvirt",
    "source_commit": "fixture",
    "workflow": "fixture",
    "installer_sha256": installer_sha,
    "installer_asset": "install.sh",
    "schema_version": schema,
    "upgrade_from": {"min_version": min_version},
}
bundle["manifest.json"] = (json.dumps(manifest) + "\n").encode()
lines = [
    f"{hashlib.sha256(data).hexdigest()}  ./{path}"
    for path, data in sorted(bundle.items())
]
bundle["SHA256SUMS"] = ("\n".join(lines) + "\n").encode()
with tarfile.open(out, "w:gz") as tar:
    for path, data in sorted(bundle.items()):
        info = tarfile.TarInfo(f"./{root}/{path}")
        info.size = len(data)
        info.mode = 0o755 if path.endswith(".sh") or path.startswith("bin/") else 0o644
        tar.addfile(info, io.BytesIO(data))
PY
}

# ----------------------------------------------------------------- servers ----

ENDPOINT_PORT="$(free_port)"
CONTROL_PORT=18080
COMPUTE_PORT=9100
# The release endpoint serves the fixture assets per release and obeys a
# mode file the cases rewrite: list mode (releases API answer), sha mode
# (normal|wrong), serve mode (on|off), schema mode (normal|99).
ENDPOINT_MODE="$WORK_DIR/endpoint.mode"
printf 'list=empty\nsha=normal\nserve=on\nschema=normal\n' >"$ENDPOINT_MODE"

# The fixture releases live under WORK_DIR so the endpoint can serve real
# files for every asset.
RELEASE_ROOT="$WORK_DIR/releases"
mkdir -p "$RELEASE_ROOT/v$TARGET_VERSION" "$RELEASE_ROOT/v$FENCED_VERSION" \
  "$RELEASE_ROOT/v$DOWNGRADE_TARGET"
build_release_tarball "$TARGET_VERSION" "$SCHEMA_VERSION" "$INSTALLED_VERSION" \
  "$RELEASE_ROOT/v$TARGET_VERSION/o3k-$TARGET_VERSION-linux-x86_64.tar.gz"
build_release_tarball "$TARGET_VERSION" "99" "$INSTALLED_VERSION" \
  "$RELEASE_ROOT/v$TARGET_VERSION/o3k-$TARGET_VERSION-linux-x86_64.tar.gz.schema99"
build_release_tarball "$FENCED_VERSION" "$SCHEMA_VERSION" "$TARGET_VERSION" \
  "$RELEASE_ROOT/v$FENCED_VERSION/o3k-$FENCED_VERSION-linux-x86_64.tar.gz"
build_release_tarball "$DOWNGRADE_TARGET" "$SCHEMA_VERSION" "$INSTALLED_VERSION" \
  "$RELEASE_ROOT/v$DOWNGRADE_TARGET/o3k-$DOWNGRADE_TARGET-linux-x86_64.tar.gz"

# Extract the published install.sh asset for each release (byte-identical to
# the bundled one) and write the published .sha256 sidecars.
python3 - "$RELEASE_ROOT" "$TARGET_VERSION" "$FENCED_VERSION" "$DOWNGRADE_TARGET" <<'PY'
import hashlib
import pathlib
import sys
import tarfile

release_root = pathlib.Path(sys.argv[1])
for version in sys.argv[2:]:
    directory = release_root / f"v{version}"
    tarball = directory / f"o3k-{version}-linux-x86_64.tar.gz"
    with tarfile.open(tarball, "r:gz") as tar:
        install = tar.extractfile(f"./o3k-{version}/packaging/get-o3k.sh").read()
        sha = tar.extractfile(f"./o3k-{version}/SHA256SUMS").read()
        manifest = tar.extractfile(f"./o3k-{version}/manifest.json").read()
    (directory / "install.sh").write_bytes(install)
    (directory / "install.sh.bytes").write_bytes(sha + b"\n---\n" + manifest)
    (tarball.with_suffix(tarball.suffix + ".sha256")).write_text(
        f"{hashlib.sha256(tarball.read_bytes()).hexdigest()}  o3k-{version}-linux-x86_64.tar.gz\n",
        encoding="utf-8",
    )
    schema99 = tarball.with_name(tarball.name + ".schema99")
    if schema99.is_file():
        schema99.with_suffix(schema99.suffix + ".sha256").write_text(
            f"{hashlib.sha256(schema99.read_bytes()).hexdigest()}  o3k-{version}-linux-x86_64.tar.gz\n",
            encoding="utf-8",
        )
PY

cat >"$WORK_DIR/endpoint.py" <<'PY'
import http.server
import pathlib
import sys

ROOT = pathlib.Path(sys.argv[1])
MODE = pathlib.Path(sys.argv[2])
LOG = pathlib.Path(sys.argv[3])


def read_modes():
    modes = {}
    for line in MODE.read_text(encoding="utf-8").splitlines():
        if "=" in line:
            key, value = line.split("=", 1)
            modes[key.strip()] = value.strip()
    return modes


class Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        with LOG.open("a", encoding="utf-8") as stream:
            stream.write("GET " + self.path + "\n")
        modes = read_modes()
        if self.path.startswith("/api/"):
            if modes.get("list") == "releases":
                # Dynamic list: every release fixture dir under ROOT is
                # advertised with the canonical asset names and full URLs
                # pointing back at this endpoint (the engine downloads
                # through O3K_UPGRADE_RELEASES_URL).
                import json as _json
                port = self.server.server_address[1]
                base = f"http://127.0.0.1:{port}"
                entries = []
                for release_dir in sorted(ROOT.iterdir()):
                    if not release_dir.is_dir():
                        continue
                    version = release_dir.name[1:]
                    assets = []
                    for name in (
                        f"o3k-{version}-linux-x86_64.tar.gz",
                        f"o3k-{version}-linux-x86_64.tar.gz.sha256",
                        "install.sh",
                    ):
                        assets.append({
                            "name": name,
                            "browser_download_url":
                                f"{base}/releases/v{version}/{name}",
                        })
                    entries.append({
                        "tag_name": "v" + version,
                        "name": "v" + version,
                        "assets": assets,
                    })
                body = (_json.dumps(entries) + "\n").encode()
                self.send_response(200)
            else:
                body = b"[]\n"
                self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        if not self.path.startswith("/releases/"):
            body = b'{"error":{"message":"not found"}}\n'
            self.send_response(404)
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        relative = self.path[len("/releases/"):]
        parts = relative.split("/")
        if len(parts) != 2:
            self.send_error(404)
            return
        version, asset = parts[0], parts[1]
        if modes.get("serve") == "off":
            self.send_error(404)
            return

        def resolve(asset):
            # Case fixtures mutate the served bytes while keeping the public
            # asset names: corrupt serves a truncated tarball (real digest),
            # schema=99 serves the migration-failure variant.
            if modes.get("serve") == "corrupt" \
                    and (ROOT / version / "corrupt.tar.gz").is_file():
                if asset.endswith(".tar.gz"):
                    return ROOT / version / "corrupt.tar.gz"
                if asset.endswith(".tar.gz.sha256"):
                    return ROOT / version / "corrupt.tar.gz.sha256"
            if modes.get("schema") == "99":
                if asset.endswith("linux-x86_64.tar.gz"):
                    return ROOT / version / (asset + ".schema99")
                if asset.endswith("linux-x86_64.tar.gz.sha256"):
                    # The fixture sidecar naming is <tarball>.schema99.sha256.
                    return ROOT / version / (asset.removesuffix(".sha256") + ".schema99.sha256")
            return ROOT / version / asset

        path = resolve(asset)
        if not path.is_file():
            self.send_error(404)
            return
        data = path.read_bytes()
        if asset.endswith(".sha256") and modes.get("sha") == "wrong":
            data = b"0000000000000000000000000000000000000000000000000000000000000000  o3k-0.3.0-alpha.1-linux-x86_64.tar.gz\n"
        self.send_response(200)
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def log_message(self, *args):
        pass


http.server.HTTPServer(("127.0.0.1", int(sys.argv[4])), Handler).serve_forever()
PY
python3 "$WORK_DIR/endpoint.py" "$RELEASE_ROOT" "$ENDPOINT_MODE" \
  "$WORK_DIR/endpoint.log" "$ENDPOINT_PORT" &
SERVER_PIDS+=($!)

# Health control files: `healthy` serves 200s, `unhealthy` serves 503s on the
# control plane so a post-start doctor run fails (case 13).
CONTROL_HEALTH="$WORK_DIR/control-health"
COMPUTE_HEALTH="$WORK_DIR/compute-health"
printf 'healthy\n' >"$CONTROL_HEALTH"
printf 'healthy\n' >"$COMPUTE_HEALTH"

# Control-plane loopback shim: /healthz, /readyz, /v3, /placement, and
# POST /v3/auth/tokens. The sentinel password must never appear in any
# captured output.
SENTINEL='SENTINEL_PW_7x9z'
python3 - "$CONTROL_HEALTH" "$WORK_DIR/control-requests.log" <<'PY' &
import http.server
import pathlib
import sys

HEALTH = pathlib.Path(sys.argv[1])
LOG = pathlib.Path(sys.argv[2])


class Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        with LOG.open("a", encoding="utf-8") as stream:
            stream.write(self.path + "\n")
        healthy = HEALTH.read_text(encoding="utf-8").strip() == "healthy"
        if self.path in ("/healthz", "/readyz"):
            body = b'{"status":"ok"}\n'
            self.send_response(200 if healthy else 503)
        elif self.path in ("/v3", "/placement"):
            body = b'{"status":"ok"}\n'
            self.send_response(200 if healthy else 503)
        else:
            body = b'{"error":{"message":"not found"}}\n'
            self.send_response(404)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self):
        if self.path == "/v3/auth/tokens":
            body = b'{"token":{"expires_at":"2099-01-01T00:00:00Z"}}\n'
            self.send_response(201)
            self.send_header("X-Subject-Token", "sandbox-token")
        else:
            body = b'{"error":{"message":"not found"}}\n'
            self.send_response(404)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *args):
        pass


http.server.HTTPServer(("127.0.0.1", 18080), Handler).serve_forever()
PY
SERVER_PIDS+=($!)

# Compute-agent loopback shim: /healthz + /readyz with the identity body whose
# epoch matches the sandbox database epoch.
python3 - "$COMPUTE_HEALTH" <<'PY' &
import http.server
import pathlib
import sys

HEALTH = pathlib.Path(sys.argv[1])
READY = (
    b'{"status":"ready","agent_id":"compute-agent",'
    b'"agent_epoch":"epoch-sandbox","software_version":"0.2.0-alpha.2",'
    b'"capabilities":{"max_vcpus":8,"max_memory_mib":16384,"max_disk_gb":10}}\n'
)


class Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        healthy = HEALTH.read_text(encoding="utf-8").strip() == "healthy"
        if self.path == "/healthz":
            body = b'{"status":"alive"}\n'
            self.send_response(200 if healthy else 503)
        elif self.path == "/readyz":
            body = READY
            self.send_response(200 if healthy else 503)
        else:
            body = b'{"error":{"message":"not found"}}\n'
            self.send_response(404)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *args):
        pass


http.server.HTTPServer(("127.0.0.1", 9100), Handler).serve_forever()
PY
SERVER_PIDS+=($!)

# The fixture servers must actually answer before any case could rely on
# them (bounded retry; no external network).
servers_ready=0
for attempt in $(seq 1 100); do
  if python3 - "$ENDPOINT_PORT" 2>/dev/null <<'PY'
import http.client
import sys

connection = http.client.HTTPConnection("127.0.0.1", int(sys.argv[1]), timeout=5)
connection.request("GET", "/api/releases")
response = connection.getresponse()
response.read()
if response.status != 200:
    raise SystemExit(1)
PY
  then
    servers_ready=1
    break
  fi
  sleep 0.1
done
if [[ "$servers_ready" -eq 1 ]]; then
  record_pass "release endpoint shim answers on the loopback"
else
  record_fail "release endpoint shim did not answer on the loopback"
fi
health_ready=0
for attempt in $(seq 1 100); do
  if python3 - 2>/dev/null <<'PY'
import http.client

for port in (18080, 9100):
    connection = http.client.HTTPConnection("127.0.0.1", port, timeout=5)
    connection.request("GET", "/healthz")
    response = connection.getresponse()
    response.read()
    if response.status != 200:
        raise SystemExit(1)
PY
  then
    health_ready=1
    break
  fi
  sleep 0.1
done
if [[ "$health_ready" -eq 1 ]]; then
  record_pass "control/compute health shims answer on 127.0.0.1:18080 and :9100"
else
  record_fail "health shims did not answer (ports 18080/9100 occupied?)"
fi

# ------------------------------------------------------- sandbox builder -----

# build_sandbox DIR — a complete healthy fixture install of v0.2.0-alpha.2
# under DIR (prefix/bin with real SHA256SUMS, /etc/o3k-style config with a
# complete mTLS identity, WAL SQLite with _sqlx_migrations up to 0017 and
# placement/epoch rows, compute network ownership, a foreign canary that must
# never change, and active systemctl units).
build_sandbox() {
  local dir="$1" prefix config data
  prefix="$dir/prefix"
  config="$dir/config"
  data="$dir/data"
  mkdir -p "$prefix/bin" "$prefix/share/o3k" "$config/tls" \
    "$data/compute/network" "$data/compute/dhcp" "$dir/systemctl-state"
  touch "$dir/systemctl-state/o3kd.active" "$dir/systemctl-state/compute.active"

  printf 'fixture installed binary o3kd %s\n' "$INSTALLED_VERSION" >"$prefix/bin/o3kd"
  printf 'fixture installed binary o3k %s\n' "$INSTALLED_VERSION" >"$prefix/bin/o3k"
  printf 'fixture installed binary o3k-compute %s\n' "$INSTALLED_VERSION" >"$prefix/bin/o3k-compute"
  chmod 0755 "$prefix/bin/o3kd" "$prefix/bin/o3k" "$prefix/bin/o3k-compute"

  cat >"$prefix/share/o3k/.o3k-installed" <<EOF
o3k-installed-v1 prefix=$prefix
bin/o3kd
bin/o3k
bin/o3k-compute
share/o3k/release-manifest.json
share/o3k/SHA256SUMS
EOF
  printf '{"version":"%s","profile":"libvirt","schema_version":"%s","upgrade_from":{"min_version":"0.1.0-alpha.1"}}\n' \
    "$INSTALLED_VERSION" "$SCHEMA_VERSION" >"$prefix/share/o3k/release-manifest.json"
  {
    sha256sum "$prefix/bin/o3kd" | awk '{print $1 "  " $2}'
    sha256sum "$prefix/bin/o3k" | awk '{print $1 "  " $2}'
    sha256sum "$prefix/bin/o3k-compute" | awk '{print $1 "  " $2}'
  } >"$prefix/share/o3k/SHA256SUMS"

  AGENT_FINGERPRINT="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  cat >"$config/o3kd.env" <<EOF
O3K_LISTEN_ADDR=127.0.0.1:18080
O3K_BOOTSTRAP_PASSWORD=$SENTINEL
O3K_TOKEN_SIGNING_KEY=$SENTINEL
O3K_DATA_DIR=$data
O3K_PROVIDER=agent
O3K_COMPUTE_AUTHORIZED_AGENTS=compute-agent=$AGENT_FINGERPRINT
EOF
  cat >"$config/o3k-compute.env" <<EOF
O3K_COMPUTE_HEALTH_ADDR=127.0.0.1:9100
O3K_COMPUTE_DATA_DIR=$data/compute
O3K_COMPUTE_MAX_DISK_GB=10
EOF
  cat >"$config/admin-openrc" <<EOF
export OS_AUTH_URL=http://127.0.0.1:18080/v3
export OS_USERNAME=admin
export OS_PASSWORD=$SENTINEL
export OS_PROJECT_NAME=admin
export OS_USER_DOMAIN_NAME=Default
export OS_PROJECT_DOMAIN_NAME=Default
export OS_REGION_NAME=RegionOne
export OS_INTERFACE=public
export OS_IDENTITY_API_VERSION=3
EOF
  cat >"$config/clouds.yaml" <<EOF
clouds:
  o3k:
    auth:
      auth_url: http://127.0.0.1:18080/v3
      username: admin
      password: $SENTINEL
EOF
  chmod 0600 "$config/o3kd.env" "$config/o3k-compute.env" \
    "$config/admin-openrc" "$config/clouds.yaml"
  for file in ca.pem server.pem server-key.pem agent.pem agent-key.pem agent-id agent-fingerprint; do
    printf 'test fixture\n' >"$config/tls/$file"
  done
  printf '%s\n' "$AGENT_FINGERPRINT" >"$config/tls/agent-fingerprint"
  printf 'compute-agent\n' >"$config/tls/agent-id"
  chmod 0600 "$config/tls/"*

  python3 - "$data/o3k.sqlite" <<'PY'
import sqlite3
import sys

connection = sqlite3.connect(sys.argv[1])
connection.execute("PRAGMA journal_mode=WAL")
connection.executescript(
    """
    CREATE TABLE placement_providers (
        id TEXT PRIMARY KEY NOT NULL,
        node_id TEXT NOT NULL UNIQUE,
        state TEXT NOT NULL,
        generation INTEGER NOT NULL
    );
    CREATE TABLE placement_inventories (
        provider_id TEXT NOT NULL REFERENCES placement_providers(id) ON DELETE CASCADE,
        resource_class TEXT NOT NULL,
        total INTEGER NOT NULL,
        reserved INTEGER NOT NULL,
        allocation_ratio REAL NOT NULL,
        used INTEGER NOT NULL,
        PRIMARY KEY (provider_id, resource_class)
    );
    CREATE TABLE observation_watermarks (agent_epoch TEXT);
    CREATE TABLE agent_commands (agent_id TEXT, agent_epoch TEXT);
    CREATE TABLE resources (
        id TEXT PRIMARY KEY NOT NULL,
        kind TEXT NOT NULL,
        desired_state TEXT NOT NULL,
        observed_state TEXT NOT NULL
    );
    CREATE TABLE network_ports (
        id TEXT PRIMARY KEY NOT NULL,
        binding_host TEXT,
        binding_state TEXT,
        status TEXT NOT NULL
    );
    CREATE TABLE placement_allocations (
        id TEXT PRIMARY KEY NOT NULL,
        provider_id TEXT NOT NULL,
        consumer_id TEXT NOT NULL
    );
    CREATE TABLE placement_allocation_resources (
        allocation_id TEXT NOT NULL,
        resource_class TEXT NOT NULL,
        amount INTEGER NOT NULL,
        PRIMARY KEY (allocation_id, resource_class)
    );
    CREATE TABLE _sqlx_migrations (
        version BIGINT PRIMARY KEY,
        description TEXT NOT NULL,
        installed_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        success BOOLEAN NOT NULL,
        checksum BLOB NOT NULL,
        execution_time BIGINT NOT NULL
    );
    """
)
for version in range(1, 18):
    connection.execute(
        "INSERT INTO _sqlx_migrations (version, description, success, checksum, execution_time)"
        " VALUES (?, ?, 1, x'00', 0)",
        (version, f"migration {version:04d}"),
    )
connection.execute(
    "INSERT INTO placement_providers VALUES ('provider-1', 'node-1', 'active', 1)"
)
for resource_class, total in (("VCPU", 8), ("MEMORY_MB", 16384), ("DISK_GB", 10)):
    connection.execute(
        "INSERT INTO placement_inventories VALUES ('provider-1', ?, ?, 0, 1.0, 0)",
        (resource_class, total),
    )
connection.execute(
    "INSERT INTO observation_watermarks (agent_epoch) VALUES ('epoch-sandbox')"
)
connection.commit()
connection.close()
PY
  chmod 0600 "$data/o3k.sqlite"
  cat >"$data/compute/network/ownership.json" <<'EOF'
{"bridge": {"name": "o3k-br0", "created_by_o3k": true}, "taps": {}}
EOF
  printf 'foreign canary — must never change\n' >"$data/foreign-canary"
}

# snapshot_fixture DIR OUT — sha256 of every file under the install fixture
# (prefix, config, data only; engine outputs like state/backups/download/logs
# are asserted separately), the byte-level no-mutation reference.
snapshot_fixture() {
  # SQLite WAL sidecars are transient by design (created/removed on
  # connection open/close), so they are excluded from the byte-level
  # no-mutation reference.
  (cd "$1" && find ./prefix ./config ./data -type f \
    ! -name 'o3k.sqlite-wal' ! -name 'o3k.sqlite-shm' \
    -print0 | sort -z | xargs -0 sha256sum | sha256sum | awk '{print $1}')
}

# db_schema_version DB — max applied _sqlx_migrations version (the §7 ruler).
db_schema_version() {
  python3 - "$1" <<'PY'
import sqlite3
import sys

connection = sqlite3.connect(sys.argv[1])
try:
    rows = connection.execute(
        "SELECT COALESCE(MAX(version), 0) FROM _sqlx_migrations"
    ).fetchall()
except sqlite3.Error:
    raise SystemExit("unreadable")
print(rows[0][0])
connection.close()
PY
}

# json_assert DESC FILE EXPECTED — python3 helper for JSON document
# assertions. EXPECTED is a JSON object whose keys may be dot-paths into the
# document; each must be present and equal. A missing FILE fails.
json_assert() {
  python3 - "$1" "$2" "$3" <<'PY'
import json
import sys

desc, path, expected_text = sys.argv[1], sys.argv[2], sys.argv[3]
try:
    document = json.load(open(path, encoding="utf-8"))
except Exception as error:
    print(f"FAIL {desc} ({path} is not parseable JSON: {error})")
    raise SystemExit(1)
expected = json.loads(expected_text)
mismatches = []
for dotted, wanted in expected.items():
    node = document
    for key in dotted.split("."):
        if isinstance(node, dict) and key in node:
            node = node[key]
        else:
            node = None
            break
    if node != wanted:
        mismatches.append(f"{dotted}: expected {wanted!r}, got {node!r}")
if mismatches:
    print(f"FAIL {desc} ({'; '.join(mismatches)}; document: {document!r})")
    raise SystemExit(1)
print(f"ok   {desc}")
PY
}

# json_refute DESC FILE EXPECTED — python3 helper asserting that each dotted
# key is ABSENT from the document or differs from the given value. Used to
# pin "state is not committed" without guessing the exact terminal phase.
json_refute() {
  python3 - "$1" "$2" "$3" <<'PY'
import json
import sys

desc, path, expected_text = sys.argv[1], sys.argv[2], sys.argv[3]
document = json.load(open(path, encoding="utf-8"))
expected = json.loads(expected_text)
violations = []
for dotted, forbidden in expected.items():
    node = document
    for key in dotted.split("."):
        if isinstance(node, dict) and key in node:
            node = node[key]
        else:
            node = None
            break
    if node == forbidden:
        violations.append(f"{dotted}: forbidden value {forbidden!r} present")
if violations:
    print(f"FAIL {desc} ({'; '.join(violations)}; document: {document!r})")
    raise SystemExit(1)
print(f"ok   {desc}")
PY
}

# ------------------------------------------------------ engine invocation ----

CARGO="${CARGO:-cargo}"
BIN="$ROOT_DIR/target/debug/o3k"
HAVE_ENGINE=0
if ! command -v "$CARGO" >/dev/null 2>&1; then
  record_skip "upgrade engine matrix requires cargo (set CARGO=/path/to/cargo); skipping binary assertions"
else
  if "$CARGO" build --manifest-path "$ROOT_DIR/Cargo.toml" -p o3k >"$OUT_DIR/cargo-build.log" 2>&1; then
    record_pass "cargo build -p o3k succeeded"
  else
    record_fail "cargo build -p o3k failed (see $OUT_DIR/cargo-build.log)"
  fi
  if [[ -x "$BIN" ]]; then
    # Capability probe: the binary must carry the upgrade CLI surface and the
    # sandbox override variables before the matrix can drive it.
    if "$BIN" --version >"$OUT_DIR/version.out" 2>"$OUT_DIR/version.err"; then
      record_pass "o3k --version exits 0"
    else
      record_skip "o3k --version is not implemented yet (bins/o3k crate in progress)"
    fi
    if command -v strings >/dev/null 2>&1 \
      && grep -q 'O3K_UPGRADE_' < <(strings "$BIN"); then
      HAVE_ENGINE=1
      record_pass "o3k binary carries the O3K_UPGRADE_* sandbox overrides"
    else
      record_skip "upgrade engine matrix (no O3K_UPGRADE_* overrides in the binary; covered by bins/o3k unit tests until the engine lands)"
    fi
  else
    record_skip "o3k binary missing after build ($BIN); skipping engine matrix"
  fi
fi

# run_engine CASE OUT ERR ARGS... — drives the real binary against one
# sandbox with all overrides + shims, recording the exit code.
run_engine() {
  local case_dir="$1" out="$2" err="$3" status=0
  shift 3
  set +e
  O3K_UPGRADE_PREFIX="$case_dir/prefix" \
  O3K_UPGRADE_BIN_DIR="$case_dir/prefix/bin" \
  O3K_UPGRADE_CONFIG_DIR="$case_dir/config" \
  O3K_UPGRADE_DATA_DIR="$case_dir/data" \
  O3K_UPGRADE_STATE_FILE="$case_dir/state.json" \
  O3K_UPGRADE_BACKUP_DIR="$case_dir/backups" \
  O3K_UPGRADE_DOWNLOAD_DIR="$case_dir/download" \
  O3K_UPGRADE_RELEASES_URL="http://127.0.0.1:$ENDPOINT_PORT/api/" \
  O3K_UPGRADE_ASSUME_ROOT=1 \
  O3K_DOCTOR_CONFIG_DIR="$case_dir/config" \
  O3K_DOCTOR_DATA_DIR="$case_dir/data" \
  O3K_DOCTOR_PREFIX="$case_dir/prefix" \
  O3K_TEST_ENDPOINT="http://127.0.0.1:$ENDPOINT_PORT" \
  O3K_TEST_SYSTEMCTL_LOG="$case_dir/systemctl.log" \
  O3K_TEST_SYSTEMCTL_STATE="$case_dir/systemctl-state" \
  O3K_TEST_SCRIPT_LOG="$case_dir/scripts.log" \
  PATH="$SHIM_BIN:$PATH" \
  "$BIN" "$@" >"$out" 2>"$err"
  status=$?
  set -e
  printf '%d' "$status" >"$case_dir/exit"
  # Never propagate the engine's exit code: callers assert it from
  # $case_dir/exit, and a non-zero return would abort the script under
  # `set -e` before the assertions run.
  return 0
}

# new_case NAME — fresh sandbox + fresh per-case logs + default fixture modes.
new_case() {
  local name="$1"
  local dir="$WORK_DIR/cases/$name"
  mkdir -p "$dir"
  build_sandbox "$dir"
  : >"$dir/systemctl.log"
  : >"$dir/scripts.log"
  printf 'list=empty\nsha=normal\nserve=on\nschema=normal\n' >"$ENDPOINT_MODE"
  printf 'healthy\n' >"$CONTROL_HEALTH"
  printf 'healthy\n' >"$COMPUTE_HEALTH"
  unset O3K_TEST_DF_MODE O3K_TEST_DOCTOR_SHIM_MODE 2>/dev/null || true
  snapshot_fixture "$dir" >"$dir/snapshot.before"
  printf '%s' "$dir"
}

# case_exit CASE_DIR — the recorded exit code.
case_exit() { cat "$1/exit"; }

# ------------------------------------------------------- engine matrix -------

if [[ "$HAVE_ENGINE" -eq 1 ]]; then
  # 1. fresh `upgrade --check` with no resolvable target reports
  #    check_blocked (the API listing is empty) — read-only, no mutation.
  case_dir="$(new_case check-blocked)"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case1.out" "$OUT_DIR/case1.err" upgrade --check --json
  set -e
  if [[ "$(case_exit "$case_dir")" -eq 1 ]]; then
    if grep -Eqi 'check_blocked' "$OUT_DIR/case1.out" "$OUT_DIR/case1.err"; then
      record_pass "upgrade --check without a resolvable target reports check_blocked (exit 1)"
    else
      record_fail "upgrade --check without a target did not report check_blocked (see $OUT_DIR/case1.out, $OUT_DIR/case1.err)"
    fi
  else
    record_fail "upgrade --check without a target exited $(case_exit "$case_dir") (expected 1)"
  fi
  [[ ! -e "$case_dir/state.json" ]] \
    && record_pass "check_blocked left no upgrade state file" \
    || record_fail "check_blocked left an upgrade state file"
  [[ -z "$(find "$case_dir/download" -mindepth 1 -print -quit 2>/dev/null || true)" ]] \
    && record_pass "check_blocked downloaded nothing" \
    || record_fail "check_blocked downloaded release assets"
  if [[ "$(snapshot_fixture "$case_dir")" = "$(cat "$case_dir/snapshot.before")" ]]; then
    record_pass "check_blocked mutated nothing in the fixture install"
  else
    record_fail "check_blocked modified a fixture file"
  fi

  # 1b. `upgrade --check --to <resolvable>` passes read-only (exit 0).
  case_dir="$(new_case check-ok)"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case1b.out" "$OUT_DIR/case1b.err" upgrade --check --to "v$TARGET_VERSION" --json
  set -e
  if [[ "$(case_exit "$case_dir")" -eq 0 ]]; then
    record_pass "upgrade --check with a resolvable target exits 0"
  else
    record_fail "upgrade --check with a resolvable target exited $(case_exit "$case_dir") (see $OUT_DIR/case1b.err)"
  fi
  [[ ! -e "$case_dir/state.json" ]] \
    && record_pass "read-only check left no upgrade state file" \
    || record_fail "read-only check left an upgrade state file"
  if [[ "$(snapshot_fixture "$case_dir")" = "$(cat "$case_dir/snapshot.before")" ]]; then
    record_pass "read-only check mutated nothing in the fixture install"
  else
    record_fail "read-only check modified a fixture file"
  fi

  # 2. downgrade request refused (exit 1, no mutation).
  case_dir="$(new_case downgrade)"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case2.out" "$OUT_DIR/case2.err" upgrade --to "v$DOWNGRADE_TARGET" --yes --json
  set -e
  if [[ "$(case_exit "$case_dir")" -eq 1 ]] \
    && grep -Eqi 'downgrade' "$OUT_DIR/case2.out" "$OUT_DIR/case2.err"; then
    record_pass "downgrade request refused with a clear message (exit 1)"
  else
    record_fail "downgrade request was not refused (exit $(case_exit "$case_dir"); see $OUT_DIR/case2.out, $OUT_DIR/case2.err)"
  fi
  [[ ! -e "$case_dir/state.json" && -z "$(find "$case_dir/backups" -mindepth 1 -print -quit 2>/dev/null || true)" ]] \
    && record_pass "downgrade refusal left no state and no backup" \
    || record_fail "downgrade refusal left state or backup content"
  if [[ "$(snapshot_fixture "$case_dir")" = "$(cat "$case_dir/snapshot.before")" ]]; then
    record_pass "downgrade refusal mutated nothing"
  else
    record_fail "downgrade refusal modified a fixture file"
  fi

  # 3. same-version upgrade is safe and non-mutating: the engine either
  #    reports a no-op success or refuses with a clear message (plan §14) —
  #    both are pinned to exit code {0,1} with zero mutation.
  case_dir="$(new_case same-version)"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case3.out" "$OUT_DIR/case3.err" upgrade --to "v$INSTALLED_VERSION" --yes --json
  set -e
  status3="$(case_exit "$case_dir")"
  if [[ "$status3" -eq 0 || "$status3" -eq 1 ]]; then
    record_pass "same-version upgrade exits $status3 (no-op success or clear refusal)"
  else
    record_fail "same-version upgrade exited $status3 (expected 0 or 1)"
  fi
  [[ -z "$(find "$case_dir/backups" -mindepth 1 -print -quit 2>/dev/null || true)" ]] \
    && record_pass "same-version upgrade created no backup" \
    || record_fail "same-version upgrade created a backup"
  if [[ "$(snapshot_fixture "$case_dir")" = "$(cat "$case_dir/snapshot.before")" ]]; then
    record_pass "same-version upgrade mutated nothing"
  else
    record_fail "same-version upgrade modified a fixture file"
  fi

  # 4. unsupported upgrade path: the target's upgrade_from.min_version is
  #    newer than the installed version -> refused.
  case_dir="$(new_case unsupported-path)"
  printf 'list=releases\nsha=normal\nserve=on\nschema=normal\n' >"$ENDPOINT_MODE"
  
  set +e
  run_engine "$case_dir" "$OUT_DIR/case4.out" "$OUT_DIR/case4.err" upgrade --to "v$FENCED_VERSION" --yes --json
  set -e
  if [[ "$(case_exit "$case_dir")" -eq 1 ]] \
    && grep -Eqi 'unsupported upgrade path|reinstall' "$OUT_DIR/case4.out" "$OUT_DIR/case4.err"; then
    record_pass "unsupported upgrade path refused (exit 1)"
  else
    record_fail "unsupported upgrade path was not refused (exit $(case_exit "$case_dir"); see $OUT_DIR/case4.err)"
  fi
  [[ ! -e "$case_dir/state.json" && -z "$(find "$case_dir/backups" -mindepth 1 -print -quit 2>/dev/null || true)" ]] \
    && record_pass "unsupported-path refusal left no state and no backup" \
    || record_fail "unsupported-path refusal left state or backup content"
  if [[ "$(snapshot_fixture "$case_dir")" = "$(cat "$case_dir/snapshot.before")" ]]; then
    record_pass "unsupported-path refusal mutated nothing"
  else
    record_fail "unsupported-path refusal modified a fixture file"
  fi

  # 5. checksum failure: the endpoint serves a wrong published digest -> no
  #    mutation, state cleared.
  case_dir="$(new_case bad-checksum)"
  printf 'list=empty\nsha=wrong\nserve=on\nschema=normal\n' >"$ENDPOINT_MODE"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case5.out" "$OUT_DIR/case5.err" upgrade --to "v$TARGET_VERSION" --yes --json
  set -e
  if [[ "$(case_exit "$case_dir")" -eq 1 ]]; then
    record_pass "checksum failure aborts the upgrade (exit 1)"
  else
    record_fail "checksum failure was accepted (exit $(case_exit "$case_dir"))"
  fi
  [[ ! -e "$case_dir/state.json" ]] \
    && record_pass "checksum failure cleared the upgrade state" \
    || record_fail "checksum failure left an upgrade state file"
  [[ -z "$(find "$case_dir/backups" -mindepth 1 -print -quit 2>/dev/null || true)" ]] \
    && record_pass "checksum failure created no backup" \
    || record_fail "checksum failure created a backup"
  if [[ "$(snapshot_fixture "$case_dir")" = "$(cat "$case_dir/snapshot.before")" ]]; then
    record_pass "checksum failure mutated nothing"
  else
    record_fail "checksum failure modified a fixture file"
  fi

  # 6. corrupt archive: a truncated tarball with a matching published digest
  #    (verification passes, extraction fails) -> no mutation.
  case_dir="$(new_case corrupt-archive)"
  tarball="$RELEASE_ROOT/v$TARGET_VERSION/o3k-$TARGET_VERSION-linux-x86_64.tar.gz"
  tarball_size="$(stat -c %s "$tarball")"
  head -c $((tarball_size / 2)) "$tarball" >"$RELEASE_ROOT/v$TARGET_VERSION/corrupt.tar.gz"
  printf '%s  o3k-%s-linux-x86_64.tar.gz\n' \
    "$(sha256sum "$RELEASE_ROOT/v$TARGET_VERSION/corrupt.tar.gz" | awk '{print $1}')" "$TARGET_VERSION" \
    >"$RELEASE_ROOT/v$TARGET_VERSION/corrupt.tar.gz.sha256"
  printf 'list=empty\nsha=normal\nserve=corrupt\nschema=normal\n' >"$ENDPOINT_MODE"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case6.out" "$OUT_DIR/case6.err" upgrade --to "v$TARGET_VERSION" --yes --json
  set -e
  if [[ "$(case_exit "$case_dir")" -eq 1 ]]; then
    record_pass "corrupt archive aborts the upgrade (exit 1)"
  else
    record_fail "corrupt archive was accepted (exit $(case_exit "$case_dir"))"
  fi
  [[ ! -e "$case_dir/state.json" ]] \
    && record_pass "corrupt archive cleared the upgrade state" \
    || record_fail "corrupt archive left an upgrade state file"
  [[ -z "$(find "$case_dir/backups" -mindepth 1 -print -quit 2>/dev/null || true)" ]] \
    && record_pass "corrupt archive created no backup" \
    || record_fail "corrupt archive created a backup"
  if [[ "$(snapshot_fixture "$case_dir")" = "$(cat "$case_dir/snapshot.before")" ]]; then
    record_pass "corrupt archive mutated nothing"
  else
    record_fail "corrupt archive modified a fixture file"
  fi

  # 7. missing release asset (404) -> no mutation.
  case_dir="$(new_case missing-asset)"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case7.out" "$OUT_DIR/case7.err" upgrade --to v9.9.9-alpha.1 --yes --json
  set -e
  if [[ "$(case_exit "$case_dir")" -eq 1 ]]; then
    record_pass "missing release asset aborts the upgrade (exit 1)"
  else
    record_fail "missing release asset was accepted (exit $(case_exit "$case_dir"))"
  fi
  [[ ! -e "$case_dir/state.json" && -z "$(find "$case_dir/backups" -mindepth 1 -print -quit 2>/dev/null || true)" ]] \
    && record_pass "missing asset left no state and no backup" \
    || record_fail "missing asset left state or backup content"
  if [[ "$(snapshot_fixture "$case_dir")" = "$(cat "$case_dir/snapshot.before")" ]]; then
    record_pass "missing asset mutated nothing"
  else
    record_fail "missing asset modified a fixture file"
  fi

  # 8. corrupt current SQLite at preflight -> refused, no backup created.
  case_dir="$(new_case corrupt-db)"
  printf 'this is not a sqlite database\n' >"$case_dir/data/o3k.sqlite"
  chmod 0600 "$case_dir/data/o3k.sqlite"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case8.out" "$OUT_DIR/case8.err" upgrade --to "v$TARGET_VERSION" --yes --json
  set -e
  if [[ "$(case_exit "$case_dir")" -eq 1 ]]; then
    record_pass "corrupt SQLite refused at preflight (exit 1)"
  else
    record_fail "corrupt SQLite was not refused (exit $(case_exit "$case_dir"))"
  fi
  [[ -z "$(find "$case_dir/backups" -mindepth 1 -print -quit 2>/dev/null || true)" ]] \
    && record_pass "corrupt SQLite produced no backup" \
    || record_fail "corrupt SQLite produced a backup"
  [[ "$(sha256sum "$case_dir/prefix/bin/o3kd" | awk '{print $1}')" \
    = "$(grep 'bin/o3kd' "$case_dir/prefix/share/o3k/SHA256SUMS" | awk '{print $1}')" ]] \
    && record_pass "corrupt SQLite left the installed binaries untouched" \
    || record_fail "corrupt SQLite case modified an installed binary"

  # 9. insufficient disk at preflight (df shim) -> refused.
  case_dir="$(new_case low-disk)"
  export O3K_TEST_DF_MODE=tiny
  set +e
  run_engine "$case_dir" "$OUT_DIR/case9.out" "$OUT_DIR/case9.err" upgrade --to "v$TARGET_VERSION" --yes --json
  set -e
  if [[ "$(case_exit "$case_dir")" -eq 1 ]]; then
    record_pass "insufficient disk refused at preflight (exit 1)"
  else
    record_fail "insufficient disk was not refused (exit $(case_exit "$case_dir"))"
  fi
  [[ -z "$(find "$case_dir/backups" -mindepth 1 -print -quit 2>/dev/null || true)" ]] \
    && record_pass "insufficient disk produced no backup" \
    || record_fail "insufficient disk produced a backup"
  if [[ "$(snapshot_fixture "$case_dir")" = "$(cat "$case_dir/snapshot.before")" ]]; then
    record_pass "insufficient disk mutated nothing"
  else
    record_fail "insufficient disk modified a fixture file"
  fi
  unset O3K_TEST_DF_MODE

  # 10. interrupted backup: the backup directory path is blocked by a
  #     regular file (root-proof: mkdir through a file fails for everyone),
  #     so the backup phase fails -> no mutation after, terminal state.
  case_dir="$(new_case backup-fails)"
  printf 'blocks the backup directory\n' >"$case_dir/backups"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case10.out" "$OUT_DIR/case10.err" upgrade --to "v$TARGET_VERSION" --yes --json
  set -e
  if [[ "$(case_exit "$case_dir")" -eq 1 ]]; then
    record_pass "backup failure aborts the upgrade (exit 1)"
  else
    record_fail "backup failure was not aborted (exit $(case_exit "$case_dir"))"
  fi
  [[ "$(cat "$case_dir/backups")" = "blocks the backup directory" ]] \
    && record_pass "failed backup wrote no backup content" \
    || record_fail "failed backup replaced the blocking file with backup content"
  if [[ "$(snapshot_fixture "$case_dir")" = "$(cat "$case_dir/snapshot.before")" ]]; then
    record_pass "backup failure mutated nothing"
  else
    record_fail "backup failure modified a fixture file"
  fi
  if [[ -e "$case_dir/state.json" ]]; then
    json_refute "backup failure leaves a non-committed terminal state" \
      "$case_dir/state.json" '{"status": "committed"}'
  else
    record_pass "backup failure cleared the state file"
  fi

  # 11. interrupted binary switch: the last-switched binary target is an
  #     un-renameable non-empty directory, so the switch fails partway and
  #     the old binary set is restored.
  case_dir="$(new_case switch-fails)"
  rm -f "$case_dir/prefix/bin/o3k"
  mkdir -p "$case_dir/prefix/bin/o3k"
  printf 'blocks rename\n' >"$case_dir/prefix/bin/o3k/blocker"
  o3kd_before="$(sha256sum "$case_dir/prefix/bin/o3kd" | awk '{print $1}')"
  compute_before="$(sha256sum "$case_dir/prefix/bin/o3k-compute" | awk '{print $1}')"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case11.out" "$OUT_DIR/case11.err" upgrade --to "v$TARGET_VERSION" --yes --json
  set -e
  if [[ "$(case_exit "$case_dir")" -eq 1 ]]; then
    record_pass "interrupted binary switch aborts (exit 1)"
  else
    record_fail "interrupted binary switch was not aborted (exit $(case_exit "$case_dir"))"
  fi
  if [[ "$(sha256sum "$case_dir/prefix/bin/o3kd" | awk '{print $1}')" = "$o3kd_before" \
    && "$(sha256sum "$case_dir/prefix/bin/o3k-compute" | awk '{print $1}')" = "$compute_before" ]]; then
    record_pass "old binary set restored after the interrupted switch"
  else
    record_fail "a binary was left modified after the interrupted switch"
  fi
  if [[ -e "$case_dir/state.json" ]]; then
    json_refute "interrupted switch leaves a non-committed terminal state" \
      "$case_dir/state.json" '{"status": "committed"}'
  else
    # A preflight refusal of the un-renameable binary target is the same
    # safety property (old binaries intact, nothing committed).
    record_pass "interrupted switch refused at preflight (no state, no mutation)"
  fi

  # 12. migration failure: the target manifest declares schema_version 99
  #     while the (fake) o3kd start does not advance the DB -> rollback
  #     attempted, old binaries and DB restored.
  case_dir="$(new_case migration-fails)"
  printf 'list=releases\nsha=normal\nserve=on\nschema=99\n' >"$ENDPOINT_MODE"
  
  set +e
  run_engine "$case_dir" "$OUT_DIR/case12.out" "$OUT_DIR/case12.err" upgrade --to "v$TARGET_VERSION" --yes --json
  set -e
  if [[ "$(case_exit "$case_dir")" -eq 1 ]]; then
    record_pass "migration failure aborts the upgrade (exit 1)"
  else
    record_fail "migration failure was not aborted (exit $(case_exit "$case_dir"))"
  fi
  if [[ "$(db_schema_version "$case_dir/data/o3k.sqlite")" = "$SCHEMA_VERSION" ]] \
    && python3 - "$case_dir/data/o3k.sqlite" <<'PY'
import sqlite3
import sys

connection = sqlite3.connect(sys.argv[1])
rows = connection.execute(
    "SELECT COUNT(*) FROM placement_providers WHERE id = 'provider-1'"
).fetchall()
assert rows[0][0] == 1, "placement row lost"
PY
  then
    record_pass "migration failure left the pre-upgrade database intact"
  else
    record_fail "migration failure damaged the database"
  fi
  if [[ "$(cat "$case_dir/prefix/bin/o3kd")" = "fixture installed binary o3kd $INSTALLED_VERSION" ]]; then
    record_pass "migration failure restored the old binary set"
  else
    record_fail "migration failure left the new binaries installed"
  fi
  if [[ -z "$(find "$case_dir/backups" -mindepth 1 -print -quit 2>/dev/null || true)" ]]; then
    record_fail "migration failure recorded no backup (rollback evidence expected)"
  else
    record_pass "migration failure recorded the backup for recovery"
  fi
  if grep -Eqi 'rollback' "$OUT_DIR/case12.out" "$OUT_DIR/case12.err"; then
    record_pass "migration failure reports the rollback"
  else
    record_fail "migration failure output does not mention the rollback"
  fi

  # 13. doctor failure after start: unhealthy control-plane shim -> not
  #     committed, rollback to the old binaries.
  case_dir="$(new_case doctor-fails)"
  printf 'list=releases\nsha=normal\nserve=on\nschema=normal\n' >"$ENDPOINT_MODE"
  
  printf 'unhealthy\n' >"$CONTROL_HEALTH"
  export O3K_TEST_DOCTOR_SHIM_MODE=unhealthy
  set +e
  run_engine "$case_dir" "$OUT_DIR/case13.out" "$OUT_DIR/case13.err" upgrade --to "v$TARGET_VERSION" --yes --json
  set -e
  printf 'healthy\n' >"$CONTROL_HEALTH"
  unset O3K_TEST_DOCTOR_SHIM_MODE
  if [[ "$(case_exit "$case_dir")" -eq 1 ]]; then
    record_pass "doctor failure after start aborts the upgrade (exit 1)"
  else
    record_fail "doctor failure after start was not aborted (exit $(case_exit "$case_dir"))"
  fi
  if [[ "$(cat "$case_dir/prefix/bin/o3kd")" = "fixture installed binary o3kd $INSTALLED_VERSION" ]]; then
    record_pass "doctor failure rolled back to the old binary set"
  else
    record_fail "doctor failure left the new binaries installed"
  fi
  if [[ -e "$case_dir/state.json" ]]; then
    json_refute "doctor failure leaves a non-committed terminal state" \
      "$case_dir/state.json" '{"status": "committed"}'
  else
    record_pass "doctor failure cleared the state file after the rollback"
  fi

  # 14. rollback with no valid backup -> refused.
  case_dir="$(new_case rollback-no-backup)"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case14.out" "$OUT_DIR/case14.err" rollback --yes --json
  set -e
  if [[ "$(case_exit "$case_dir")" -eq 1 ]] \
    && grep -Eqi 'backup|rollback' "$OUT_DIR/case14.out" "$OUT_DIR/case14.err"; then
    record_pass "rollback with no valid backup refused (exit 1)"
  else
    record_fail "rollback with no backup was not refused (exit $(case_exit "$case_dir"); see $OUT_DIR/case14.err)"
  fi
  if [[ "$(snapshot_fixture "$case_dir")" = "$(cat "$case_dir/snapshot.before")" ]]; then
    record_pass "rollback with no backup mutated nothing"
  else
    record_fail "rollback with no backup modified a fixture file"
  fi

  # 15. rollback with a tampered backup (flipped byte in backup.json) ->
  #     refused, the committed install stays untouched.
  case_dir="$(new_case rollback-tampered)"
  printf 'list=releases\nsha=normal\nserve=on\nschema=normal\n' >"$ENDPOINT_MODE"
  
  set +e
  run_engine "$case_dir" "$OUT_DIR/case15-up.out" "$OUT_DIR/case15-up.err" upgrade --to "v$TARGET_VERSION" --yes --json
  up_status=$?
  set -e
  if [[ "$up_status" -eq 0 ]]; then
    record_pass "tamper case: initial upgrade committed (exit 0)"
  else
    record_fail "tamper case: initial upgrade failed (exit $up_status; see $OUT_DIR/case15-up.err)"
  fi
  backup_json="$(find "$case_dir/backups" -name backup.json -print -quit 2>/dev/null || true)"
  [[ -n "$backup_json" && -s "$backup_json" ]] \
    && record_pass "tamper case: a backup record exists" \
    || record_fail "tamper case: no backup record found"
  if [[ -n "$backup_json" ]]; then
    sed -i 's/"source_version"/"source_version_corrupted"/' "$backup_json" # the record must fail validation
    set +e
    run_engine "$case_dir" "$OUT_DIR/case15.out" "$OUT_DIR/case15.err" rollback --yes --json
    set -e
    if [[ "$(case_exit "$case_dir")" -eq 1 ]]; then
      record_pass "rollback with a tampered backup refused (exit 1)"
    else
      record_fail "rollback accepted a tampered backup (exit $(case_exit "$case_dir"))"
    fi
    if [[ "$(cat "$case_dir/prefix/bin/o3kd")" = "fixture release binary o3kd $TARGET_VERSION" ]]; then
      record_pass "tampered-backup rollback left the committed install untouched"
    else
      record_fail "tampered-backup rollback modified the committed binaries"
    fi
  fi

  # 16. second rollback -> no-op notice, no mutation.
  case_dir="$(new_case second-rollback)"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case16-up.out" "$OUT_DIR/case16-up.err" upgrade --to "v$TARGET_VERSION" --yes --json
  up_status=$?
  set -e
  [[ "$up_status" -eq 0 ]] || record_fail "second-rollback case: initial upgrade failed (exit $up_status)"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case16-rb.out" "$OUT_DIR/case16-rb.err" rollback --yes --json
  rb_status=$?
  set -e
  [[ "$rb_status" -eq 0 ]] || record_fail "second-rollback case: first rollback failed (exit $rb_status)"
  snapshot_after_rollback="$(snapshot_fixture "$case_dir")"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case16.out" "$OUT_DIR/case16.err" rollback --yes --json
  set -e
  status16="$(case_exit "$case_dir")"
  if [[ "$status16" -eq 0 || "$status16" -eq 1 ]] \
    && grep -Eqi 'rollback|backup' "$OUT_DIR/case16.out" "$OUT_DIR/case16.err"; then
    record_pass "second rollback is a no-op with a notice (exit $status16)"
  else
    record_fail "second rollback behaved unexpectedly (exit $status16; see $OUT_DIR/case16.err)"
  fi
  if [[ "$(snapshot_fixture "$case_dir")" = "$snapshot_after_rollback" ]]; then
    record_pass "second rollback mutated nothing"
  else
    record_fail "second rollback modified a fixture file"
  fi

  # 17. concurrent upgrade: the engine's lock file (<state-file>.lock,
  #     O_EXCL with dead-pid reclaim) is pre-created with a live pid, a
  #     second invocation must refuse.
  case_dir="$(new_case concurrent)"
  LOCK_FILE="$case_dir/state.json.lock"
  printf '%s\n' "$$" >"$LOCK_FILE"
  set +e
  O3K_UPGRADE_PREFIX="$case_dir/prefix" \
  O3K_UPGRADE_BIN_DIR="$case_dir/prefix/bin" \
  O3K_UPGRADE_CONFIG_DIR="$case_dir/config" \
  O3K_UPGRADE_DATA_DIR="$case_dir/data" \
  O3K_UPGRADE_STATE_FILE="$case_dir/state.json" \
  O3K_UPGRADE_BACKUP_DIR="$case_dir/backups" \
  O3K_UPGRADE_DOWNLOAD_DIR="$case_dir/download" \
  O3K_UPGRADE_RELEASES_URL="http://127.0.0.1:$ENDPOINT_PORT/api/" \
  O3K_UPGRADE_ASSUME_ROOT=1 \
  O3K_DOCTOR_CONFIG_DIR="$case_dir/config" \
  O3K_DOCTOR_DATA_DIR="$case_dir/data" \
  O3K_DOCTOR_PREFIX="$case_dir/prefix" \
  O3K_TEST_ENDPOINT="http://127.0.0.1:$ENDPOINT_PORT" \
  O3K_TEST_SYSTEMCTL_LOG="$case_dir/systemctl.log" \
  O3K_TEST_SYSTEMCTL_STATE="$case_dir/systemctl-state" \
  O3K_TEST_SCRIPT_LOG="$case_dir/scripts.log" \
  PATH="$SHIM_BIN:$PATH" \
  timeout 20 "$BIN" upgrade --to "v$TARGET_VERSION" --yes --json \
    >"$OUT_DIR/case17.out" 2>"$OUT_DIR/case17.err"
  status17=$?
  set -e
  printf '%d' "$status17" >"$case_dir/exit"
  rm -f "$LOCK_FILE"
  # 1 = explicit concurrent refusal (also accepts 124 for a bounded wait).
  if [[ "$status17" -eq 1 || "$status17" -eq 124 ]]; then
    record_pass "concurrent upgrade refused while the lock is held (exit $status17)"
  else
    record_fail "concurrent upgrade was not refused (exit $status17; see $OUT_DIR/case17.err)"
  fi
  if [[ "$(snapshot_fixture "$case_dir")" = "$(cat "$case_dir/snapshot.before")" ]]; then
    record_pass "concurrent upgrade mutated nothing"
  else
    record_fail "concurrent upgrade modified a fixture file"
  fi

  # 18. happy path: full upgrade -> rollback -> re-upgrade with all shims
  #     healthy; state COMMITTED, service order correct, and the fixture
  #     identity (config files, DB rows) preserved end-to-end.
  case_dir="$(new_case happy-path)"
  printf 'list=releases\nsha=normal\nserve=on\nschema=normal\n' >"$ENDPOINT_MODE"
  
  config_before="$(cd "$case_dir/config" && find . -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | awk '{print $1}')"
  set +e
  run_engine "$case_dir" "$OUT_DIR/case18-up.out" "$OUT_DIR/case18-up.err" upgrade --to "v$TARGET_VERSION" --yes --json
  up_status=$?
  set -e
  if [[ "$up_status" -eq 0 ]]; then
    record_pass "happy path: upgrade committed (exit 0)"
  else
    record_fail "happy path: upgrade failed (exit $up_status; see $OUT_DIR/case18-up.out, $OUT_DIR/case18-up.err)"
  fi
  if python3 - "$case_dir" "$INSTALLED_VERSION" "$TARGET_VERSION" <<'PY'
import hashlib
import pathlib
import sys

case_dir = pathlib.Path(sys.argv[1])
installed, target = sys.argv[2], sys.argv[3]
prefix = case_dir / "prefix"

def read(path):
    return path.read_bytes()

old_binary = f"fixture installed binary o3kd {installed}\n".encode()
new_binary = f"fixture release binary o3kd {target}\n".encode()
assert read(prefix / "bin/o3kd") == new_binary, "o3kd was not switched"
assert read(prefix / "bin/o3k") == f"fixture release binary o3k {target}\n".encode(), "o3k was not switched"
assert read(prefix / "bin/o3k-compute") == f"fixture release binary o3k-compute {target}\n".encode(), "o3k-compute was not switched"
import json

manifest = json.loads(read(prefix / "share/o3k/release-manifest.json"))
assert manifest["version"] == target, manifest
PY
  then
    record_pass "happy path: new binaries + release manifest installed"
  else
    record_fail "happy path: binaries or release manifest are wrong after upgrade"
  fi
  [[ ! -e "$case_dir/state.json" ]] \
    && record_pass "happy path: committed upgrade cleared the in-progress state" \
    || record_fail "happy path: upgrade left an in-progress state file"
  if [[ -s "$case_dir/backups/backup-chain.json" ]] \
    && python3 - "$case_dir/backups/backup-chain.json" <<'PY'
import json
import sys

document = json.load(open(sys.argv[1], encoding="utf-8"))
entries = document.get("backups", document if isinstance(document, list) else [])
assert len(entries) >= 1, "chain has no entries"
PY
  then
    record_pass "happy path: backup chain records the committed backup"
  else
    record_fail "happy path: backup chain missing or empty"
  fi
  if [[ "$(db_schema_version "$case_dir/data/o3k.sqlite")" = "$SCHEMA_VERSION" ]] \
    && python3 - "$case_dir/data/o3k.sqlite" <<'PY'
import sqlite3
import sys

connection = sqlite3.connect(sys.argv[1])
rows = connection.execute(
    "SELECT COUNT(*) FROM placement_providers WHERE id = 'provider-1'"
).fetchall()
assert rows[0][0] == 1, "placement row lost"
PY
  then
    record_pass "happy path: database identity preserved (schema + placement rows)"
  else
    record_fail "happy path: database identity damaged"
  fi
  if grep -q '^stop o3k-compute' "$case_dir/systemctl.log" \
    && grep -q '^stop o3kd' "$case_dir/systemctl.log" \
    && grep -q '^start o3kd' "$case_dir/systemctl.log" \
    && grep -q '^start o3k-compute' "$case_dir/systemctl.log"; then
    compute_stop="$(grep -n '^stop o3k-compute' "$case_dir/systemctl.log" | head -n1 | cut -d: -f1)"
    control_stop="$(grep -n '^stop o3kd' "$case_dir/systemctl.log" | head -n1 | cut -d: -f1)"
    control_start="$(grep -n '^start o3kd' "$case_dir/systemctl.log" | head -n1 | cut -d: -f1)"
    compute_start="$(grep -n '^start o3k-compute' "$case_dir/systemctl.log" | head -n1 | cut -d: -f1)"
    if [[ "$compute_stop" -lt "$control_stop" && "$control_stop" -lt "$control_start" \
      && "$control_start" -lt "$compute_start" ]]; then
      record_pass "happy path: service order is compute-stop -> o3kd-stop -> o3kd-start -> compute-start"
    else
      record_fail "happy path: service stop/start order violated (see $case_dir/systemctl.log)"
    fi
  else
    record_fail "happy path: systemctl shim did not record the stop/start sequence"
  fi
  if [[ "$(cd "$case_dir/config" && find . -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | awk '{print $1}')" = "$config_before" ]]; then
    record_pass "happy path: config identity (env files, credentials, TLS) preserved through upgrade"
  else
    record_fail "happy path: a configuration file changed during the upgrade"
  fi

  # 18 continued: rollback.
  set +e
  run_engine "$case_dir" "$OUT_DIR/case18-rb.out" "$OUT_DIR/case18-rb.err" rollback --yes --json
  rb_status=$?
  set -e
  if [[ "$rb_status" -eq 0 ]]; then
    record_pass "happy path: rollback succeeds (exit 0)"
  else
    record_fail "happy path: rollback failed (exit $rb_status; see $OUT_DIR/case18-rb.err)"
  fi
  if python3 - "$case_dir" "$INSTALLED_VERSION" <<'PY'
import pathlib
import sys

case_dir = pathlib.Path(sys.argv[1])
installed = sys.argv[2]
prefix = case_dir / "prefix"
assert prefix.joinpath("bin/o3kd").read_bytes() == f"fixture installed binary o3kd {installed}\n".encode()
PY
  then
    record_pass "happy path: rollback restored the old binary set"
  else
    record_fail "happy path: rollback did not restore the old binaries"
  fi
  if python3 - "$case_dir/data/o3k.sqlite" <<'PY'
import sqlite3
import sys

connection = sqlite3.connect(sys.argv[1])
rows = connection.execute(
    "SELECT COUNT(*) FROM placement_providers WHERE id = 'provider-1'"
).fetchall()
assert rows[0][0] == 1, "placement row lost"
PY
  then
    record_pass "happy path: rollback preserved the database"
  else
    record_fail "happy path: rollback damaged the database"
  fi

  # 18 continued: re-upgrade proves upgrade-after-rollback.
  set +e
  run_engine "$case_dir" "$OUT_DIR/case18-re.out" "$OUT_DIR/case18-re.err" upgrade --to "v$TARGET_VERSION" --yes --json
  re_status=$?
  set -e
  if [[ "$re_status" -eq 0 ]] \
    && [[ "$(cat "$case_dir/prefix/bin/o3kd")" = "fixture release binary o3kd $TARGET_VERSION" ]]; then
    record_pass "happy path: re-upgrade after rollback succeeds"
  else
    record_fail "happy path: re-upgrade failed (exit $re_status; see $OUT_DIR/case18-re.err)"
  fi
  [[ ! -e "$case_dir/state.json" ]] \
    && record_pass "happy path: re-upgrade ended COMMITTED (state cleared)" \
    || record_fail "happy path: re-upgrade left an in-progress state file"
  if [[ "$(cd "$case_dir/config" && find . -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | awk '{print $1}')" = "$config_before" ]]; then
    record_pass "happy path: config identity preserved through upgrade + rollback + re-upgrade"
  else
    record_fail "happy path: a configuration file changed across the full journey"
  fi
  grep -Fqx 'foreign canary — must never change' "$case_dir/data/foreign-canary" \
    && record_pass "happy path: foreign fixture file untouched" \
    || record_fail "happy path: foreign fixture file modified"
fi

# Secret-safety: no output may ever carry the sandbox sentinel.
if grep -rq "$SENTINEL" "$OUT_DIR" 2>/dev/null; then
  record_fail "a sentinel secret leaked into captured output"
  grep -rn "$SENTINEL" "$OUT_DIR" >&2 || true
else
  record_pass "no sentinel secret appears in any captured output"
fi

printf 'upgrade process tests: %d passed, %d failed, %d skipped\n' "$PASS" "$FAIL" "$SKIP"
[[ $FAIL -eq 0 ]]
