[package]
name = "o3k-scheduler"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
o3k-placement = { path = "../o3k-placement" }
thiserror.workspace = true

[dev-dependencies]
o3k-store = { path = "../o3k-store" }
tokio.workspace = true
uuid.workspace = true
